### ISSUE TITLE
Comparison with the Potential Energy Loss on Gibbs distribution

### ISSUE THREAD

**Issue by rose-jinyang** [RElbers/region-mutual-information-pytorch#2]
Hello
How are you?
Thanks for contributing to this project.
Did u look at this paper?
https://www.mdpi.com/2072-4292/13/3/454
The author of this paper says that the Potential Energy Loss on Gibbs distribution outperforms your RMI loss.
Excuse me, is that really true?
I think that u can easily implement the PE loss and compare it with your RMI loss.
If u can implement the PE loss, could u share the code?
Thanks.

**Comment by RElbers** [comment]
It's possible that that loss works better for some problems. Unfortunately, I don't have the time to implement it.
